.add-key:
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - cat /home/.ssh/id_rsa
    # echo "/home/.ssh/id_rsa" | tr -d '\r' | ssh-add - 
    - ssh-add /home/.ssh/id_rsa
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    #- ssh-keyscan 172.21.0.11 >> ~/.ssh/known_hosts
    #- ssh-keyscan 172.21.0.12 >> ~/.ssh/known_hosts
    #- ssh-keyscan 172.21.0.13 >> ~/.ssh/known_hosts
    #- chmod 644 ~/.ssh/known_hosts
    #- '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >> ~/.ssh/config'
.keyscan:
  before_script:
    - ssh-keyscan 172.21.0.11 >> ~/.ssh/known_hosts
    - ssh-keyscan 172.21.0.12 >> ~/.ssh/known_hosts
    - ssh-keyscan 172.21.0.13 >> ~/.ssh/known_hosts
